_BASE_: [
  '../datasets/my_coco.yml',
  '../runtime.yml',
  '_base_/picodet_v2.yml',
  '_base_/optimizer_300e.yml',
  '_base_/picodet_320_reader.yml',
]
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/PPLCNet_x0_75_pretrained.pdparams
weights: 
find_unused_parameters: True
use_ema: true
epoch: 10
snapshot_epoch: 5
LCNet:
  scale: 0.75
  feature_maps: [3, 4, 5]
LCPAN:
  out_channels: 96
PicoHeadV2:
  conv_feat:
    name: PicoFeat
    feat_in: 96
    feat_out: 96
    num_convs: 2
    num_fpn_stride: 4
    norm_type: bn
    share_cls_reg: True
    use_se: True
  feat_in_chan: 96
TrainReader:
  batch_transforms:

  - BatchRandomResize: {target_size: 320, random_size: False, random_interp: False, interp: 2, keep_ratio: True, letterbox: True, pad_val: 114}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  - PadGT: {}
  batch_size: 8
  num_workers: 2
EvalReader:
  sample_transforms:
  - Decode: {}
  - LetterboxResize: {target_size: [320, 320], pad_val: 114, interp: 2}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  - PadGT: {}
  batch_size: 8
  shuffle: false
TestReader:
  inputs_def:
    image_shape: [1, 3, 320, 320]
  sample_transforms:
  - Decode: {}
  - LetterboxResize: {target_size: [320, 320], pad_val: 114, interp: 2}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_size: 1
LearningRate:
  base_lr: 0.02
  schedulers:
  - !CosineDecay
    max_epochs: 5
  - !LinearWarmup
    start_factor: 0.1
    steps: 200
